# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MWI4OGFlNjE3MjViYmRlMTg4Mzc2ZTA5MzU4ZTczYjA3ZTU0YmM4NTRiOTkzNzc1ZTUxOWQzNzk3YmI0OTlmZTAyYmJkYWJlNDFiYmVkNDJmMGY0ZmYyZTkxZmYyNjgyZmIwNjU4Yzg4ZDI4YzA5NDVmMDBmNWM2OTYwNTM3MzI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
